// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTWvAfblxYGE3VoXwOgiQUotWN8a7oU_M',
    appId: '1:808298909071:web:0c35b714e100474d588ffa',
    messagingSenderId: '808298909071',
    projectId: 'test-8fb47',
    authDomain: 'test-8fb47.firebaseapp.com',
    storageBucket: 'test-8fb47.appspot.com',
    measurementId: 'G-6B7EWV1LSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnjzeO0H38Dby_SkU-KsSL8fvmUaw8FG4',
    appId: '1:808298909071:android:7a5be9bda36080c8588ffa',
    messagingSenderId: '808298909071',
    projectId: 'test-8fb47',
    storageBucket: 'test-8fb47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGOxt1m4wLqz7dVX0qTBpezDjQOVixgWg',
    appId: '1:808298909071:ios:c72a92ec7ee57943588ffa',
    messagingSenderId: '808298909071',
    projectId: 'test-8fb47',
    storageBucket: 'test-8fb47.appspot.com',
    iosClientId: '808298909071-los6rtt6pr020l5nmtkc19u5f125q1n4.apps.googleusercontent.com',
    iosBundleId: 'com.toppickfootball.toppick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGOxt1m4wLqz7dVX0qTBpezDjQOVixgWg',
    appId: '1:808298909071:ios:80839b3a82b85f9d588ffa',
    messagingSenderId: '808298909071',
    projectId: 'test-8fb47',
    storageBucket: 'test-8fb47.appspot.com',
    iosClientId: '808298909071-c5qcbudjsjvi6v6gmg0enll06l0dbmv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsapp',
  );
}
