List<Map<String, String>> demoLeagues = [
  {
    'leagueId': "1",
    'leagueName': 'Premier League',
    'leagueCode': 'PL',
    'countryCode': 'England',
    'countryName': 'England',
    'logo': 'assets/icons/epl.png',
    'isFavorite': "false",
  },
  // {
  //   'leagueId': "2",
  //   'leagueName': 'Bundesliga',
  //   'countryCode': 'Germany',
  //   'countryName': 'Germany',
  //   'logo': 'assets/icons/laliga.png',
  //   'isFavorite': "false",
  // },
  {
    'leagueId': "3",
    'leagueName': 'La Liga',
    'leagueCode': 'PD',
    'countryCode': 'Spain',
    'countryName': 'Spain',
    'logo': 'assets/icons/laliga.png',
    'isFavorite': "false",
  },
  {
    'leagueId': "4",
    'leagueCode': 'SA',
    'leagueName': 'Serie A',
    'countryCode': 'Italy',
    'countryName': 'Italy',
    'logo': 'assets/icons/seriea.png',
    'isFavorite': "false",
  },
  {
    'leagueId': "5",
    'leagueName': 'Ligue 1',
    'leagueCode': 'FL1',
    'countryCode': 'France',
    'countryName': 'France',
    'logo': 'assets/icons/ligue1.png',
    'isFavorite': "false",
  },
  {
    'leagueId': "6",
    'leagueCode': 'GPL',
    'leagueName': 'Ghana Premier League',
    'countryCode': 'Ghana',
    'countryName': 'Ghana',
    'logo': 'assets/icons/gpl.png',
    'isFavorite': "false",
  },
];
